--This script extracts basic customer details from Kudos Counter Intelligence

-- Declare a temp holding table
declare @cust table(
	[ID] [int] NOT NULL PRIMARY KEY,
	[prefix] [nvarchar](200),
	[firstname] [nvarchar](200),
	[lastname] [nvarchar](200),
	[_address_telephone] [nvarchar](200),
	[email] [nvarchar](200),
	[_address_street] [nvarchar](500),
	[_address_city] [nvarchar](200),
	[_address_postcode] [nvarchar](200),
	[_address_country_id] [nvarchar](200),
	[_address_prefix] [nvarchar](200),
	[_address_firstname] [nvarchar](200),
	[_address_lastname] [nvarchar](200),
	[_website] nvarchar(50),
	[_store] nvarchar(50),
	[created_in] nvarchar(50),
	[group_id] nvarchar(50),
	[store_id] nvarchar(50),
	[website_id] nvarchar(50),
	[address_default_billing_] nvarchar(50),
	[address_default_shipping_] nvarchar(50)
	)

-- Get all customers with an email
insert into @cust
select ID, [Contact Title], [Contact FirstName], [Contact LastName], [Phone Mobile], Email,
[Address Street], [Address City], [Address Post Code], [Address Country], [Contact Title], [Contact FirstName], [Contact LastName],
null, null, null, null, null, null, null, null
from Customer c where c.code like 'e%'
and Email like '%@%' --and exists (select 1 from [Customer Invoice Header] ih where ih.[Customer ID]=c.ID)

-- Use alternative phone numbers where no cellphone was supplied
update @cust set [_address_telephone]=[Phone Home] from @cust c1, Customer c2 where c1.ID=c2.ID and c1.[_address_telephone]='' and c2.[Phone Home] !=''
update @cust set [_address_telephone]=[Phone Work] from @cust c1, Customer c2 where c1.ID=c2.ID and c1.[_address_telephone]='' and c2.[Phone Home] !=''

-- Set default values
update @cust set [_website] = 'base'
update @cust set [_store] = 'default'
update @cust set [created_in] = 'Default Store View'
update @cust set [group_id] = '1'
update @cust set [store_id] = '1'
update @cust set [website_id] = '1'
update @cust set [address_default_billing_] = '1'
update @cust set [address_default_shipping_] = '1'

-- Populate required fields
update @cust set firstname = '-' where firstname='' or firstname is null
update @cust set lastname = '-' where lastname='' or lastname is null
update @cust set _address_firstname = '-' where _address_firstname='' or _address_firstname is null
update @cust set _address_lastname = '-' where _address_lastname='' or _address_lastname is null
update @cust set _address_postcode = '-' where _address_postcode='' or _address_postcode is null
update @cust set _address_country_id = 'NZ' where _address_country_id='' or _address_country_id is null
update @cust set _address_telephone = '-' where _address_telephone='' or _address_telephone is null
update @cust set _address_country_id = 'NZ' where _address_country_id='' or _address_country_id is null

-- Update country codes
update @cust set _address_country_id = 'AD' where _address_country_id like '%Andorra%'
update @cust set _address_country_id = 'AE' where _address_country_id like '%Emirates%'
update @cust set _address_country_id = 'AF' where _address_country_id like '%Afghanistan%'
update @cust set _address_country_id = 'AG' where _address_country_id like '%Antigua%'
update @cust set _address_country_id = 'AI' where _address_country_id like '%Anguilla%'
update @cust set _address_country_id = 'AL' where _address_country_id like '%Albania%'
update @cust set _address_country_id = 'AM' where _address_country_id like '%Armenia%'
update @cust set _address_country_id = 'AO' where _address_country_id like '%Angola%'
update @cust set _address_country_id = 'AQ' where _address_country_id like '%Antarctica%'
update @cust set _address_country_id = 'AR' where _address_country_id like '%Argentina%'
update @cust set _address_country_id = 'AS' where _address_country_id like '%Samoa%'
update @cust set _address_country_id = 'AT' where _address_country_id like '%Austria%'
update @cust set _address_country_id = 'AU' where _address_country_id like '%Australia%'
update @cust set _address_country_id = 'AW' where _address_country_id like '%Aruba%'
update @cust set _address_country_id = 'AX' where _address_country_id like '%Åland%'
update @cust set _address_country_id = 'AZ' where _address_country_id like '%Azerbaijan%'
update @cust set _address_country_id = 'BA' where _address_country_id like '%Bosnia%'
update @cust set _address_country_id = 'BB' where _address_country_id like '%Barbados%'
update @cust set _address_country_id = 'BD' where _address_country_id like '%Bangladesh%'
update @cust set _address_country_id = 'BE' where _address_country_id like '%Belgium%'
update @cust set _address_country_id = 'BF' where _address_country_id like '%Burkina%'
update @cust set _address_country_id = 'BG' where _address_country_id like '%Bulgaria%'
update @cust set _address_country_id = 'BH' where _address_country_id like '%Bahrain%'
update @cust set _address_country_id = 'BI' where _address_country_id like '%Burundi%'
update @cust set _address_country_id = 'BJ' where _address_country_id like '%Benin%'
update @cust set _address_country_id = 'BL' where _address_country_id like '%Barthélemy%'
update @cust set _address_country_id = 'BM' where _address_country_id like '%Bermuda%'
update @cust set _address_country_id = 'BN' where _address_country_id like '%Brunei%'
update @cust set _address_country_id = 'BO' where _address_country_id like '%Bolivia%'
update @cust set _address_country_id = 'BQ' where _address_country_id like '%Bonaire%'
update @cust set _address_country_id = 'BR' where _address_country_id like '%Brazil%'
update @cust set _address_country_id = 'BS' where _address_country_id like '%Bahamas%'
update @cust set _address_country_id = 'BT' where _address_country_id like '%Bhutan%'
update @cust set _address_country_id = 'BV' where _address_country_id like '%Bouvet%'
update @cust set _address_country_id = 'BW' where _address_country_id like '%Botswana%'
update @cust set _address_country_id = 'BY' where _address_country_id like '%Belarus%'
update @cust set _address_country_id = 'BZ' where _address_country_id like '%Belize%'
update @cust set _address_country_id = 'CA' where _address_country_id like '%Canada%'
update @cust set _address_country_id = 'CC' where _address_country_id like '%Cocos (Keeling) Islands%'
update @cust set _address_country_id = 'CD' where _address_country_id like '%Congo, the Democratic Republic of the%'
update @cust set _address_country_id = 'CF' where _address_country_id like '%Central African Republic%'
update @cust set _address_country_id = 'CG' where _address_country_id like '%Congo%'
update @cust set _address_country_id = 'CH' where _address_country_id like '%Switzerland%'
update @cust set _address_country_id = 'CI' where _address_country_id like '%Ivoire%'
update @cust set _address_country_id = 'CK' where _address_country_id like '%Cook Islands%'
update @cust set _address_country_id = 'CL' where _address_country_id like '%Chile%'
update @cust set _address_country_id = 'CM' where _address_country_id like '%Cameroon%'
update @cust set _address_country_id = 'CN' where _address_country_id like '%China%'
update @cust set _address_country_id = 'CO' where _address_country_id like '%Colombia%'
update @cust set _address_country_id = 'CR' where _address_country_id like '%Costa Rica%'
update @cust set _address_country_id = 'CU' where _address_country_id like '%Cuba%'
update @cust set _address_country_id = 'CV' where _address_country_id like '%Verde%'
update @cust set _address_country_id = 'CW' where _address_country_id like '%Curaçao%'
update @cust set _address_country_id = 'CX' where _address_country_id like '%Christmas%'
update @cust set _address_country_id = 'CY' where _address_country_id like '%Cyprus%'
update @cust set _address_country_id = 'CZ' where _address_country_id like '%Czech%'
update @cust set _address_country_id = 'DE' where _address_country_id like '%Germany%'
update @cust set _address_country_id = 'DJ' where _address_country_id like '%Djibouti%'
update @cust set _address_country_id = 'DK' where _address_country_id like '%Denmark%'
update @cust set _address_country_id = 'DM' where _address_country_id like '%Dominica%'
update @cust set _address_country_id = 'DO' where _address_country_id like '%Dominican%'
update @cust set _address_country_id = 'DZ' where _address_country_id like '%Algeria%'
update @cust set _address_country_id = 'EC' where _address_country_id like '%Ecuador%'
update @cust set _address_country_id = 'EE' where _address_country_id like '%Estonia%'
update @cust set _address_country_id = 'EG' where _address_country_id like '%Egypt%'
update @cust set _address_country_id = 'EH' where _address_country_id like '%Western%'
update @cust set _address_country_id = 'ER' where _address_country_id like '%Eritrea%'
update @cust set _address_country_id = 'ES' where _address_country_id like '%Spain%'
update @cust set _address_country_id = 'ET' where _address_country_id like '%Ethiopia%'
update @cust set _address_country_id = 'FI' where _address_country_id like '%Finland%'
update @cust set _address_country_id = 'FJ' where _address_country_id like '%Fiji%'
update @cust set _address_country_id = 'FK' where _address_country_id like '%Falkland%'
update @cust set _address_country_id = 'FM' where _address_country_id like '%Micronesia%'
update @cust set _address_country_id = 'FO' where _address_country_id like '%Faroe%'
update @cust set _address_country_id = 'FR' where _address_country_id like '%France%'
update @cust set _address_country_id = 'GA' where _address_country_id like '%Gabon%'
update @cust set _address_country_id = 'GB' where _address_country_id like '%United Kingdom%' or _address_country_id like '%Britain%'
update @cust set _address_country_id = 'GD' where _address_country_id like '%Grenada%'
update @cust set _address_country_id = 'GE' where _address_country_id like '%Georgia%'
update @cust set _address_country_id = 'GF' where _address_country_id like '%Guiana%'
update @cust set _address_country_id = 'GG' where _address_country_id like '%Guernsey%'
update @cust set _address_country_id = 'GH' where _address_country_id like '%Ghana%'
update @cust set _address_country_id = 'GI' where _address_country_id like '%Gibraltar%'
update @cust set _address_country_id = 'GL' where _address_country_id like '%Greenland%'
update @cust set _address_country_id = 'GM' where _address_country_id like '%Gambia%'
update @cust set _address_country_id = 'GN' where _address_country_id like '%Guinea%'
update @cust set _address_country_id = 'GP' where _address_country_id like '%Guadeloupe%'
update @cust set _address_country_id = 'GQ' where _address_country_id like '%Equatorial%Guinea%'
update @cust set _address_country_id = 'GR' where _address_country_id like '%Greece%'
update @cust set _address_country_id = 'GS' where _address_country_id like '%Georgia%Sandwich%'
update @cust set _address_country_id = 'GT' where _address_country_id like '%Guatemala%'
update @cust set _address_country_id = 'GU' where _address_country_id like '%Guam%'
update @cust set _address_country_id = 'GW' where _address_country_id like '%Guinea-Bissau%'
update @cust set _address_country_id = 'GY' where _address_country_id like '%Guyana%'
update @cust set _address_country_id = 'HK' where _address_country_id like '%Hong Kong%'
update @cust set _address_country_id = 'HM' where _address_country_id like '%McDonald%'
update @cust set _address_country_id = 'HN' where _address_country_id like '%Honduras%'
update @cust set _address_country_id = 'HR' where _address_country_id like '%Croatia%'
update @cust set _address_country_id = 'HT' where _address_country_id like '%Haiti%'
update @cust set _address_country_id = 'HU' where _address_country_id like '%Hungary%'
update @cust set _address_country_id = 'ID' where _address_country_id like '%Indonesia%'
update @cust set _address_country_id = 'IE' where _address_country_id like '%Ireland%'
update @cust set _address_country_id = 'IL' where _address_country_id like '%Israel%'
update @cust set _address_country_id = 'IM' where _address_country_id like '%Isle of Man%'
update @cust set _address_country_id = 'IN' where _address_country_id like '%India%'
update @cust set _address_country_id = 'IO' where _address_country_id like '%British%Territory%'
update @cust set _address_country_id = 'IQ' where _address_country_id like '%Iraq%'
update @cust set _address_country_id = 'IR' where _address_country_id like '%Iran%'
update @cust set _address_country_id = 'IS' where _address_country_id like '%Iceland%'
update @cust set _address_country_id = 'IT' where _address_country_id like '%Italy%'
update @cust set _address_country_id = 'JE' where _address_country_id like '%Jersey%'
update @cust set _address_country_id = 'JM' where _address_country_id like '%Jamaica%'
update @cust set _address_country_id = 'JO' where _address_country_id like '%Jordan%'
update @cust set _address_country_id = 'JP' where _address_country_id like '%Japan%'
update @cust set _address_country_id = 'KE' where _address_country_id like '%Kenya%'
update @cust set _address_country_id = 'KG' where _address_country_id like '%Kyrgyzstan%'
update @cust set _address_country_id = 'KH' where _address_country_id like '%Cambodia%'
update @cust set _address_country_id = 'KI' where _address_country_id like '%Kiribati%'
update @cust set _address_country_id = 'KM' where _address_country_id like '%Comoros%'
update @cust set _address_country_id = 'KN' where _address_country_id like '%Saint Kitts and Nevis%'
update @cust set _address_country_id = 'KR' where _address_country_id like '%Korea%'
update @cust set _address_country_id = 'KW' where _address_country_id like '%Kuwait%'
update @cust set _address_country_id = 'KY' where _address_country_id like '%Cayman%'
update @cust set _address_country_id = 'KZ' where _address_country_id like '%Kazakhstan%'
update @cust set _address_country_id = 'LA' where _address_country_id like 'Lao%'
update @cust set _address_country_id = 'LB' where _address_country_id like '%Lebanon%'
update @cust set _address_country_id = 'LC' where _address_country_id like '%Saint Lucia%'
update @cust set _address_country_id = 'LI' where _address_country_id like '%Liechtenstein%'
update @cust set _address_country_id = 'LK' where _address_country_id like '%Sri Lanka%'
update @cust set _address_country_id = 'LR' where _address_country_id like '%Liberia%'
update @cust set _address_country_id = 'LS' where _address_country_id like '%Lesotho%'
update @cust set _address_country_id = 'LT' where _address_country_id like '%Lithuania%'
update @cust set _address_country_id = 'LU' where _address_country_id like '%Luxembourg%'
update @cust set _address_country_id = 'LV' where _address_country_id like '%Latvia%'
update @cust set _address_country_id = 'LY' where _address_country_id like '%Libya%'
update @cust set _address_country_id = 'MA' where _address_country_id like '%Morocco%'
update @cust set _address_country_id = 'MC' where _address_country_id like '%Monaco%'
update @cust set _address_country_id = 'MD' where _address_country_id like '%Moldova%'
update @cust set _address_country_id = 'ME' where _address_country_id like '%Montenegro%'
update @cust set _address_country_id = 'MF' where _address_country_id like '%Martin%'
update @cust set _address_country_id = 'MG' where _address_country_id like '%Madagascar%'
update @cust set _address_country_id = 'MH' where _address_country_id like '%Marshall%'
update @cust set _address_country_id = 'MK' where _address_country_id like '%Macedonia%'
update @cust set _address_country_id = 'ML' where _address_country_id like '%Mali%'
update @cust set _address_country_id = 'MM' where _address_country_id like '%Myanmar%'
update @cust set _address_country_id = 'MN' where _address_country_id like '%Mongolia%'
update @cust set _address_country_id = 'MO' where _address_country_id like '%Macao%'
update @cust set _address_country_id = 'MP' where _address_country_id like '%Mariana%'
update @cust set _address_country_id = 'MQ' where _address_country_id like '%Martinique%'
update @cust set _address_country_id = 'MR' where _address_country_id like '%Mauritania%'
update @cust set _address_country_id = 'MS' where _address_country_id like '%Montserrat%'
update @cust set _address_country_id = 'MT' where _address_country_id like '%Malta%'
update @cust set _address_country_id = 'MU' where _address_country_id like '%Mauritius%'
update @cust set _address_country_id = 'MV' where _address_country_id like '%Maldives%'
update @cust set _address_country_id = 'MW' where _address_country_id like '%Malawi%'
update @cust set _address_country_id = 'MX' where _address_country_id like '%Mexico%'
update @cust set _address_country_id = 'MY' where _address_country_id like '%Malaysia%'
update @cust set _address_country_id = 'MZ' where _address_country_id like '%Mozambique%'
update @cust set _address_country_id = 'NA' where _address_country_id like '%Namibia%'
update @cust set _address_country_id = 'NC' where _address_country_id like '%Caledonia%'
update @cust set _address_country_id = 'NE' where _address_country_id like '%Niger%'
update @cust set _address_country_id = 'NF' where _address_country_id like '%Norfolk%'
update @cust set _address_country_id = 'NG' where _address_country_id like '%Nigeria%'
update @cust set _address_country_id = 'NI' where _address_country_id like '%Nicaragua%'
update @cust set _address_country_id = 'NL' where _address_country_id like '%Netherlands%'
update @cust set _address_country_id = 'NO' where _address_country_id like '%Norway%'
update @cust set _address_country_id = 'NP' where _address_country_id like '%Nepal%'
update @cust set _address_country_id = 'NR' where _address_country_id like '%Nauru%'
update @cust set _address_country_id = 'NU' where _address_country_id like '%Niue%'
update @cust set _address_country_id = 'NZ' where _address_country_id like '%Zealand%'
update @cust set _address_country_id = 'OM' where _address_country_id like '%Oman%'
update @cust set _address_country_id = 'PA' where _address_country_id like '%Panama%'
update @cust set _address_country_id = 'PE' where _address_country_id like '%Peru%'
update @cust set _address_country_id = 'PF' where _address_country_id like '%Polynesia%'
update @cust set _address_country_id = 'PG' where _address_country_id like '%Papua%'
update @cust set _address_country_id = 'PH' where _address_country_id like '%Philippines%'
update @cust set _address_country_id = 'PK' where _address_country_id like '%Pakistan%'
update @cust set _address_country_id = 'PL' where _address_country_id like '%Poland%'
update @cust set _address_country_id = 'PM' where _address_country_id like '%Pierre%'
update @cust set _address_country_id = 'PN' where _address_country_id like '%Pitcairn%'
update @cust set _address_country_id = 'PR' where _address_country_id like '%Puerto%'
update @cust set _address_country_id = 'PS' where _address_country_id like '%Palestine%'
update @cust set _address_country_id = 'PT' where _address_country_id like '%Portugal%'
update @cust set _address_country_id = 'PW' where _address_country_id like '%Palau%'
update @cust set _address_country_id = 'PY' where _address_country_id like '%Paraguay%'
update @cust set _address_country_id = 'QA' where _address_country_id like '%Qatar%'
update @cust set _address_country_id = 'RE' where _address_country_id like '%Réunion%'
update @cust set _address_country_id = 'RO' where _address_country_id like '%Romania%'
update @cust set _address_country_id = 'RS' where _address_country_id like '%Serbia%'
update @cust set _address_country_id = 'RU' where _address_country_id like '%Russia%'
update @cust set _address_country_id = 'RW' where _address_country_id like '%Rwanda%'
update @cust set _address_country_id = 'SA' where _address_country_id like '%Saudi%'
update @cust set _address_country_id = 'SB' where _address_country_id like '%Solomon%'
update @cust set _address_country_id = 'SC' where _address_country_id like '%Seychelles%'
update @cust set _address_country_id = 'SD' where _address_country_id like '%Sudan%'
update @cust set _address_country_id = 'SE' where _address_country_id like '%Sweden%'
update @cust set _address_country_id = 'SG' where _address_country_id like '%Singapore%'
update @cust set _address_country_id = 'SH' where _address_country_id like '%Helena%'
update @cust set _address_country_id = 'SI' where _address_country_id like '%Slovenia%'
update @cust set _address_country_id = 'SJ' where _address_country_id like '%Svalbard%'
update @cust set _address_country_id = 'SK' where _address_country_id like '%Slovakia%'
update @cust set _address_country_id = 'SL' where _address_country_id like '%Sierra%'
update @cust set _address_country_id = 'SM' where _address_country_id like '%Marino%'
update @cust set _address_country_id = 'SN' where _address_country_id like '%Senegal%'
update @cust set _address_country_id = 'SO' where _address_country_id like '%Somalia%'
update @cust set _address_country_id = 'SR' where _address_country_id like '%Suriname%'
update @cust set _address_country_id = 'SS' where _address_country_id like '%Sudan%'
update @cust set _address_country_id = 'ST' where _address_country_id like '%Principe%'
update @cust set _address_country_id = 'SV' where _address_country_id like '%Salvador%'
update @cust set _address_country_id = 'SX' where _address_country_id like '%Sint Maarten%'
update @cust set _address_country_id = 'SY' where _address_country_id like '%Syrian%'
update @cust set _address_country_id = 'SZ' where _address_country_id like '%Swaziland%'
update @cust set _address_country_id = 'TC' where _address_country_id like '%Turks%'
update @cust set _address_country_id = 'TD' where _address_country_id like '%Chad%'
update @cust set _address_country_id = 'TF' where _address_country_id like '%French%Territories%'
update @cust set _address_country_id = 'TG' where _address_country_id like '%Togo%'
update @cust set _address_country_id = 'TH' where _address_country_id like '%Thailand%'
update @cust set _address_country_id = 'TJ' where _address_country_id like '%Tajikistan%'
update @cust set _address_country_id = 'TK' where _address_country_id like '%Tokelau%'
update @cust set _address_country_id = 'TL' where _address_country_id like '%Timor%'
update @cust set _address_country_id = 'TM' where _address_country_id like '%Turkmenistan%'
update @cust set _address_country_id = 'TN' where _address_country_id like '%Tunisia%'
update @cust set _address_country_id = 'TO' where _address_country_id like '%Tonga%'
update @cust set _address_country_id = 'TR' where _address_country_id like '%Turkey%'
update @cust set _address_country_id = 'TT' where _address_country_id like '%Trinidad%'
update @cust set _address_country_id = 'TV' where _address_country_id like '%Tuvalu%'
update @cust set _address_country_id = 'TW' where _address_country_id like '%Taiwan%'
update @cust set _address_country_id = 'TZ' where _address_country_id like '%Tanzania%'
update @cust set _address_country_id = 'UA' where _address_country_id like '%Ukraine%'
update @cust set _address_country_id = 'UG' where _address_country_id like '%Uganda%'
update @cust set _address_country_id = 'UM' where _address_country_id like '%U%S%Islands%'
update @cust set _address_country_id = 'US' where _address_country_id like '%U%S%A%'
update @cust set _address_country_id = 'UY' where _address_country_id like '%Uruguay%'
update @cust set _address_country_id = 'UZ' where _address_country_id like '%Uzbekistan%'
update @cust set _address_country_id = 'VA' where _address_country_id like '%Holy%'
update @cust set _address_country_id = 'VC' where _address_country_id like '%Vincent%Grenadines%'
update @cust set _address_country_id = 'VE' where _address_country_id like '%Venezuela%'
update @cust set _address_country_id = 'VG' where _address_country_id like '%Virgin%Islands%British%'
update @cust set _address_country_id = 'VI' where _address_country_id like '%Virgin%Islands%U%S%'
update @cust set _address_country_id = 'VN' where _address_country_id like '%Viet%Nam%'
update @cust set _address_country_id = 'VU' where _address_country_id like '%Vanuatu%'
update @cust set _address_country_id = 'WF' where _address_country_id like '%Wallis%Futuna%'
update @cust set _address_country_id = 'WS' where _address_country_id like '%Samoa%'
update @cust set _address_country_id = 'YE' where _address_country_id like '%Yemen%'
update @cust set _address_country_id = 'YT' where _address_country_id like '%Mayotte%'
update @cust set _address_country_id = 'ZA' where _address_country_id like '%Africa%'
update @cust set _address_country_id = 'ZM' where _address_country_id like '%Zambia%'
update @cust set _address_country_id = 'ZW' where _address_country_id like '%Zimbabwe%'


-- return the data
select * from @cust
